### ISSUE TITLE
Problem in sendSuccessAnswer when inserting in a table where primary key is auto increment key.

### ISSUE THREAD

**Issue by SidhMj** [Ardobras/mysql-to-rest#12]
Suppose we have some table where Primary Key is in Auto Increment form. Then the current version of code will throw error while inserting. 
I am proposing a fix at the time of calling the function sendSuccessAnswer in "insert" method.
 ```
var field = findPrim(columns, req.query[settings.paramPrefix + 'field']); 
                            console.log(field);
                            console.log(insertJson[field]);
                            if(insertJson[field]==='undefined'){}
                                else { sendSuccessAnswer(req.params.table , res,insertJson[field], field);}
```
If primary key is provided in input then it will show the inserted row as result. And if primary key is not present it will just show the success message.

**Comment by kenodressel** [comment]
Hello @sidharthaa ,
thanks for opening this issue. I am having troubles to understand your problem. Do you mean it throws an error if we supply an primary key when there is an auto increment primary key?

**Comment by kenodressel** [comment]
@sidharthaa If you send me more info I can repopen this issue.
