### ISSUE TITLE
Question: What is the syntax to add a character filter in the URL

### ISSUE THREAD

**Issue by jimrae** [Ardobras/mysql-to-rest#2]
This is awesome!!!
I have one question that I couldn't figure out.
If I want to have a where clause with a text string, what is  the syntax?

For example:
http://localhost:8000/api/tasks?_limit=0,10&_fields=ACTIVITYDATE,TYPE,CITY,ISCLOSED&_order[ACTIVITYDATE}=DESC&CITY=New York

I get a bad column error.

Any suggestions would be appreciated.

**Comment by kenodressel** [comment]
&_order[ACTIVITYDATE} the last bracket looks like the issue in this particular request to me. 

Regarding your question you should try CITY=New%20York :)
