### ISSUE TITLE
Error on single column POST request

### ISSUE THREAD

**Issue by texonidas** [Ardobras/mysql-to-rest#3]
I have a table with a single column, 'Description', which is the primary key. On performing a post request to this end point, the data is inserted, however request returns the following error:

{ [Error: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause']
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }

Is this caused by me not having an 'id' column?

**Comment by kenodressel** [comment]
Hey @texonidas 
Thanks for the bug report! I was able to reproduce it but came across the issue, that mysql is not returning a proper `insertId` while inserting non numeric primary keys. I stopped it from throwing an error but unfortunately can not return the just inserted entry :/ (Or at least I don't know how...)
