### ISSUE TITLE
Multiple DB Connections

### ISSUE THREAD

**Issue by ArifADS** [Ardobras/mysql-to-rest#4]
What is the good way to have multiple db connections?

My client's mysql structure is that every of his clients have his own db so I need to connect to a certain db for the client that logged in.

**Comment by kenodressel** [comment]
Hm my plugin is written to only expose one db. So you would probably need multiple node instances...

**Comment by ArifADS** [comment]
i tried with

>  localhost:5000/api/bd_krazzypizza.producto

, sending the desired db directly in the URL, but I will try  forwarding the correct params with 

> api.setAuth(function(req,res,next) {
>     if(req.isAuthenticated && req.method === 'GET'){
>         next();
>     } else {
>         //Handle unauthorized access 
>     }
> });

Thank you for the plugin, looks awesome.

**Comment by kenodressel** [comment]
Thanks! Good idea with the auth function :)
