### ISSUE TITLE
Connection pools 

### ISSUE THREAD

**Issue by simakwm** [Ardobras/mysql-to-rest#7]
Is there a way to use a [connection pool ](https://github.com/mysqljs/mysql#pooling-connections) instead of a single connection? It would be awesome.

**Comment by simakwm** [comment]
Geez, I just created a pool with mysql.createPool() and passed it to mysqltorest, like: `mysqltorest(app, pool)` and it worked(!?).

**Comment by kenodressel** [comment]
Awesome :) I will update the readme file.
